version: "2.1"
services:
  rsync-music:
    image: jswetzen/rsync-backup
    container_name: rsync-music
    environment:
      - PUID=1000
      - PGID=998
      - TZ=Europe/Madrid
      - SSH_IDENTITY_FILE=/home/joseka/.ssh/id_rsa.pub
      - BACKUPDIR=joseka@136.243.153.54:/docker
    volumes:
      - /docker/homer:/home  # origen de los archivos
      - ./destino:/backup  # destino del backup
    mem_limit: 1014M
    mem_reservation: 128M 
    restart: unless-stopped


docker run -d --name rsync-backup22 \
  --volume /docker:/backup \
  --volume /docker/homer:/home \
  --env SSH_IDENTITY_FILE=/home/joseka/.ssh/id_rsa.pub \
  --env BACKUPDIR=joseka@136.243.153.54:/docker \
  jswetzen/rsync-backup



  rsync -av -e -P 'ssh -t' joseka@136.243.153.54:/docker/ /docker/comprimidos/ 

    rsync -av -e -P ssh joseka@136.243.153.54:.ssh