version: "2.1"
services:
  rsync-music:
    image: jswetzen/rsync-backup
    container_name: rsync-music
    environment:
      - PUID=1000
      - PGID=998
      - TZ=Europe/Madrid
    volumes:
      - ./origen:/origen # origen de los archivos
      - ./destino:/destino # destino del backup
    mem_limit: 1240M
    mem_reservation: 256M 
    restart: unless-stopped
